version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb+srv://pranavghaytadakar143:dVlqoMQJQSbzmEn0@cluster0.luwl5f4.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
